---
title: "Exploring the Assimilative Capacity of Old Tampa Bay"
author: "Tampa Bay Estuary Program"
date: "`r Sys.Date()`"
format:
  html:
    theme: cosmo
    code-tools: 
      source: https://github.com/tbep-tech/explore-ass-cap/blob/main/docs/explore.qmd
    css: styles.css
toc: true
lightbox: true
execute:
  echo: false
  warning: false
---

```{r}
#| include: false
library(sf)
library(tidyverse)
library(here)
library(reactable)
library(reactablefmtr)
library(leaflet)
library(patchwork)

source(here('R/funcs.R'))

data(epcdata, package = 'tbeptools')
load(file = here('data/epcwq.RData'))
load(file = here('data/lddat.RData'))
```


```{r}
otbmo <- tbeptools::anlz_avedat(epcdata)$mos |>
  filter(bay_segment == 'OTB', var == 'mean_chla') |>
  rename(chla = val) |>
  select(-bay_segment, -var) |>
  mutate(
    date = make_date(yr, mo, day = 1)
  )

ldmo <- lddat |>
  rename(
    yr = year,
    mo = month
  ) |>
  summarise(
    tn_load = sum(tn_load),
    .by = c(yr, mo)
  ) |>
  mutate(
    date = make_date(yr, mo, day = 1)
  )

# join and create up to five month lags for tn_load
tomod <- inner_join(otbmo, ldmo, by = c('date', 'yr', 'mo')) |>
  mutate(
    tn_load_lag1 = lag(tn_load, 1),
    tn_load_lag2 = lag(tn_load, 2),
    tn_load_lag3 = lag(tn_load, 3),
    tn_load_lag4 = lag(tn_load, 4),
    tn_load_lag5 = lag(tn_load, 5),
    tn_load_lag6 = lag(tn_load, 6),
    yrcat = ifelse(yr < 2010, 'Before 2010', '2010 and After'),
  ) |>
  rename(tn_load_lag0 = tn_load) |>
  pivot_longer(
    cols = starts_with('tn_load_lag'),
    names_to = 'lag',
    values_to = 'tn_load'
  ) |>
  mutate(
    lag = str_remove(lag, 'tn_load_'),
    lag = str_replace(lag, 'lag', 'Lag ')
  )

# create scatterplots of chla vs tn_load with linear fits for each lag
pall <- ggplot(tomod, aes(x = tn_load / 10, y = chla)) +
  geom_point(alpha = 0.5, size = 0.5) +
  geom_smooth(
    method = 'lm',
    formula = y ~ x,
    color = '#F8766D',
    se = T
  ) +
  scale_x_log10() +
  scale_y_log10() +
  facet_wrap(~lag, ncol = 7) +
  labs(
    x = 'Total Nitrogen Load (0.1 x tons/month)',
    y = 'Chlorophyll-a (µg/L)',
    title = 'Monthly Relationship between Chlorophyll-a and Total Nitrogen',
    subtitle = '1995 to 2024'
  ) +
  theme_minimal()

ppre <- ggplot(
  tomod[tomod$yrcat %in% 'Before 2010', ],
  aes(x = tn_load / 10, y = chla)
) +
  geom_point(alpha = 0.5, size = 0.5) +
  geom_smooth(
    method = 'lm',
    formula = y ~ x,
    color = '#00BA38',
    se = T
  ) +
  scale_x_log10() +
  scale_y_log10() +
  facet_wrap(~lag, ncol = 7) +
  labs(
    x = 'Total Nitrogen Load (0.1 x tons/month)',
    y = 'Chlorophyll-a (µg/L)',
    subtitle = 'Before 2010'
  ) +
  theme_minimal()

ppos <- ggplot(
  tomod[tomod$yrcat %in% '2010 and After', ],
  aes(x = tn_load / 10, y = chla)
) +
  geom_point(alpha = 0.5, size = 0.5) +
  geom_smooth(
    method = 'lm',
    formula = y ~ x,
    color = '#619CFF',
    se = T
  ) +
  scale_x_log10() +
  scale_y_log10() +
  facet_wrap(~lag, ncol = 7) +
  labs(
    x = 'Total Nitrogen Load (0.1 x tons/month)',
    y = 'Chlorophyll-a (µg/L)',
    subtitle = '2010 and After'
  ) +
  theme_minimal()

pall + ppre + ppos + plot_layout(ncol = 1, axis_titles = 'collect')
```

```{r}
mod <- tomod |>
  group_nest(lag) |>
  mutate(
    model = map(data, function(x) {
      modall <- lm(log10(chla) ~ log10(tn_load), data = x)
      modpre <- lm(
        log10(chla) ~ log10(tn_load),
        data = x[x$yrcat == 'Before 2010', ]
      )
      modpos <- lm(
        log10(chla) ~ log10(tn_load),
        data = x[x$yrcat == '2010 and After', ]
      )

      # get rsq for all
      rsqall <- summary(modall)$r.squared
      rsqpre <- summary(modpre)$r.squared
      rsqpos <- summary(modpos)$r.squared

      tibble(
        rsqall = rsqall,
        rsqpre = rsqpre,
        rsqpos = rsqpos
      )
    })
  ) |>
  select(-data) |>
  unnest(model) |>
  pivot_longer(
    cols = starts_with('rsq'),
    names_to = 'period',
    values_to = 'rsq'
  ) |>
  mutate(
    lag = str_remove(lag, 'Lag '),
    period = case_when(
      period == 'rsqall' ~ '1995 to 2024',
      period == 'rsqpre' ~ 'Before 2010',
      period == 'rsqpos' ~ '2010 and After'
    ),
    period = factor(
      period,
      levels = c('1995 to 2024', 'Before 2010', '2010 and After')
    )
  )

ggplot(mod, aes(x = as.numeric(lag), y = rsq, color = period)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = 0:6) +
  labs(
    x = 'Lag in Months',
    y = expression(R^2),
    color = 'Period',
    title = 'Model fits (R²) by Lag Time and Period'
  ) +
  theme_minimal() +
  theme(legend.position = 'bottom')
```